# Generated by Django 4.1.7 on 2023-09-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_reg_no'),
        ('users', '0002_auto_20230911_2332'),
    ]

    operations = [
    ]
