# Generated by Django 4.1.7 on 2023-09-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20230913_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(default='media/forums/Dragonfruit2.jpg', upload_to='profiles'),
        ),
    ]
