# Generated by Django 4.2.4 on 2023-08-06 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='forum',
            name='mods',
            field=models.ManyToManyField(related_name='mod_forums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='users',
            field=models.ManyToManyField(related_name='forums', to=settings.AUTH_USER_MODEL),
        ),
    ]
