# Generated by Django 4.2.4 on 2023-08-06 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0003_events_is_public_alter_forum_mods_alter_forum_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='users_added',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
