# Generated by Django 2.1 on 2023-09-11 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_events_users_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='pic',
            field=models.ImageField(blank=True, default='media/forums/Dragonfruit2.jpg', upload_to='forums'),
        ),
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='events',
            name='users_added',
            field=models.ManyToManyField(blank=True, related_name='events_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
