# Generated by Django 4.1.5 on 2023-09-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_alter_events_users_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='pic',
            field=models.ImageField(default='media/forums/Dragonfruit2.jpg', upload_to='media/forums'),
        ),
    ]
